ARG ARCH
ARG NODE_VERSION
ARG OS
ARG NODE_RED_VERSION

FROM ${ARCH}/node:${NODE_VERSION}-${OS}

# Basic build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG BUILD_VERSION
ARG BUILD_REF
ARG NODE_RED_VERSION
ARG ARCH
ARG PYTHON_VERSION
ARG QEMU_ARCH
ARG OS

LABEL org.label-schema.build-date=${BUILD_DATE} \
    org.label-schema.docker.dockerfile=".docker/Dockerfile.alpine" \
    org.label-schema.license="Apache License 2.0" \
    org.label-schema.name="Node-RED" \
    org.label-schema.version=${BUILD_VERSION} \
    org.label-schema.description="Node-RED is a programming tool for wiring together hardware devices, APIs and online services in new and interesting ways." \
    org.label-schema.url="https://nodered.org" \
    org.label-schema.vcs-ref=${BUILD_REF} \
    org.label-schema.vcs-type="Git" \
    org.label-schema.vcs-url="https://github.com/node-red/node-red-docker" \
    org.label-schema.arch=${ARCH} \
    authors="Dave Conway-Jones, Nick O'Leary, James Thomas, Raymond Mouthaan"

# QEMU - Quick Emulation
COPY tmp/qemu-$QEMU_ARCH-static /usr/bin/qemu-$QEMU_ARCH-static

# Copy scripts
COPY .docker/scripts/* /tmp/

# Install tools, create Node-RED app and data dir, add user and set rights
RUN set -ex && \
    apt-get update && apt-get install -y --no-install-recommends \
        iputils-ping \
        curl \
        nano \
        git \
        openssh-client && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /usr/src/node-red /data && \
    useradd --home-dir /usr/src/node-red --no-create-home node-red && \
    chown -R node-red:node-red /data && \
    chown -R node-red:node-red /usr/src/node-red

# Install Python 2 & gpio library (Python 2.7 will reach the end of its life on January 1st, 2020!)
RUN chmod u+x /tmp/python2_gpio.sh && /tmp/python2_gpio.sh

# Install Python 3 & gpio library
RUN chmod u+x /tmp/python3_gpio.sh && /tmp/python3_gpio.sh

# Set work directory
WORKDIR /usr/src/node-red

# Run as node-red user
USER node-red

# package.json contains Node-RED NPM module and node dependencies
COPY package.json /usr/src/node-red/
RUN npm install

# Replace Python 2.7 with 3.6 in 36-rpi-gpio.js or remove Node-RED build-in rpi-gpio for non arm32v6
USER root
RUN chmod u+x /tmp/python_fix.sh && /tmp/python_fix.sh

# Cleanup tmp
RUN rm /tmp/*

# Return as node-red user
USER node-red

# Env variables
ENV NODE_RED_VERSION=$NODE_RED_VERSION
ENV FLOWS=flows.json
ENV NODE_PATH=/usr/src/node-red/node_modules:/data/node_modules

# User configuration directory volume
VOLUME ["/data"]

# Expose the listening port of node-red
EXPOSE 1880

HEALTHCHECK --interval=10s --timeout=120s --retries=3 \
      CMD curl -f http://localhost:1880 || exit 1

ENTRYPOINT ["npm", "start", "--", "--userDir", "/data"]
